version: "3.6"

services:
  koi-wiki-database:
    container_name: koi-wiki-database
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: koi_wiki
      POSTGRES_USER: koi_wiki
      POSTGRES_PASSWORD: koi_wiki

  koi-wiki-keycloak:
    container_name: koi-wiki-keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin